# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev-live" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.CI_TOKEN }}
      - name: Clone Dalamud
        run: git -C /home/runner clone https://github.com/goatcorp/dalamud-distrib.git
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        env:
          DALAMUD_HOME: /home/runner/dalamud-distrib
      - uses: actions/upload-artifact@v4
        with:
          name: MareSempiterne
          path: MareSynchronos/bin/x64/Debug/Release/MareSempiterne/latest.zip
